apiVersion: v1
kind: Secret
metadata:
  name: polling-mysql-secret
type: Opaquels
stringData:
  DATASOURCE_URL: jdbc:mysql://polling-app-mysql:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false

  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: polling_app
  MYSQL_USER: callicoder
  MYSQL_PASSWORD: callicoder

  REACT_APP_API_BASE_URL: http://polling-app-server:8080/api
